version: 0.2
        
phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Commit ID - ${Commit_ID}"
      - echo "DOING NOTHING (WIP)"
      # Updates package repositories in image
      #- apt-get -y -qq update

  pre_build:
    on-failure: ABORT
    commands:
      - echo "DOING NOTHING (WIP)"

  build:
    on-failure: ABORT
    commands:
      - echo "DOING NOTHING (WIP)"
  post_build:
    on-failure: ABORT
    commands:
      - echo "DOING NOTHING (WIP)"
      - rm -rf .terraform terraform terraform_${TF_VERSION}_linux_amd64.zip

artifacts:
  files:
    - '**/*'
